    const units = ["bottle",
        "can",
        "cl",
        "cup",
        "dash",
        "jigger",
        "kg",
        "l",
        "lb",
        "ml",
        "oz",
        "part",
        "piece",
        "pinch",
        "qt",
        "scoop",
        "shot",
        "slice",
        "tbsp",
        "tsp",];
    const glasses = ["Balloon Glass",
        "Beer Glass",
        "Beer mug",
        "Beer pilsner",
        "Brandy snifter",
        "Champagne flute",
        "Champagne Flute",
        "Cocktail glass",
        "Cocktail Glass",
        "Coffee mug",
        "Coffee Mug",
        "Collins glass",
        "Collins Glass",
        "Copper Mug",
        "Cordial glass",
        "Coupe Glass",
        "Highball glass",
        "Highball Glass",
        "Hurricane glass",
        "Irish coffee cup",
        "Jar",
        "Margarita glass",
        "Margarita/Coupette glass",
        "Martini Glass",
        "Mason jar",
        "Old-fashioned glass",
        "Old-Fashioned glass",
        "Parfait glass",
        "Pint glass",
        "Pitcher",
        "Pousse cafe glass",
        "Punch bowl",
        "Punch Bowl",
        "Shot glass",
        "Shot Glass",
        "Whiskey Glass",
        "Whiskey sour glass",
        "White wine glass",
        "Wine Glass",]

    const ingreds = [
        // Wines
        { label: "Red Wine", value: "Red Wine" },
        { label: "White Wine", value: "White Wine" },
        { label: "Rosé Wine", value: "Rosé Wine" },
        { label: "Sparkling Wine", value: "Sparkling Wine" },
        { label: "Dessert Wine", value: "Dessert Wine" },
        { label: "Fortified Wine", value: "Fortified Wine" },

        // Beers
        { label: "Lager", value: "Lager" },
        { label: "Pilsner", value: "Pilsner" },
        { label: "Ale", value: "Ale" },
        { label: "Pale Ale", value: "Pale Ale" },
        { label: "India Pale Ale (IPA)", value: "India Pale Ale (IPA)" },
        { label: "Brown Ale", value: "Brown Ale" },
        { label: "Porter", value: "Porter" },
        { label: "Stout", value: "Stout" },
        { label: "Wheat Beer", value: "Wheat Beer" },
        { label: "Sour Beer", value: "Sour Beer" },
        { label: "Craft Beer", value: "Craft Beer" },

        // Spirits
        { label: "Vodka", value: "Vodka" },
        { label: "Gin", value: "Gin" },
        { label: "Whiskey", value: "Whiskey" },
        { label: "Bourbon", value: "Bourbon" },
        { label: "Scotch", value: "Scotch" },
        { label: "Rye Whiskey", value: "Rye Whiskey" },
        { label: "Irish Whiskey", value: "Irish Whiskey" },
        { label: "Rum", value: "Rum" },
        { label: "White Rum", value: "White Rum" },
        { label: "Dark Rum", value: "Dark Rum" },
        { label: "Spiced Rum", value: "Spiced Rum" },
        { label: "Tequila", value: "Tequila" },
        { label: "Blanco Tequila", value: "Blanco Tequila" },
        { label: "Reposado Tequila", value: "Reposado Tequila" },
        { label: "Añejo Tequila", value: "Añejo Tequila" },
        { label: "Brandy", value: "Brandy" },
        { label: "Cognac", value: "Cognac" },
        { label: "Armagnac", value: "Armagnac" },
        { label: "Mezcal", value: "Mezcal" },

        // Liqueurs
        { label: "Amaretto", value: "Amaretto" },
        { label: "Baileys Irish Cream", value: "Baileys Irish Cream" },
        { label: "Triple Sec", value: "Triple Sec" },
        { label: "Cointreau", value: "Cointreau" },
        { label: "Grand Marnier", value: "Grand Marnier" },
        { label: "Kahlúa", value: "Kahlúa" },
        { label: "Sambuca", value: "Sambuca" },
        { label: "Chartreuse", value: "Chartreuse" },
        { label: "Campari", value: "Campari" },
        { label: "Aperol", value: "Aperol" },
        { label: "Vermouth (Sweet)", value: "Vermouth (Sweet)" },
        { label: "Vermouth (Dry)", value: "Vermouth (Dry)" },

        // Other Fermented Drinks
        { label: "Cider", value: "Cider" },
        { label: "Perry", value: "Perry" },
        { label: "Saké", value: "Saké" },
        { label: "Mead", value: "Mead" },
        { label: "Soju", value: "Soju" },
        { label: "Baijiu", value: "Baijiu" },]


export {
    ingreds,
    units,
    glasses
}